### ISSUE TITLE
Remove dependency on Guzzle

### ISSUE THREAD

**Issue by kadryjanek** [DocPlanner/integrations-api-sdk-php#4]
Currently this package relies on `Guzzle 6`, even though currently sufficient `PSR` standards are available to completely decouple from any particular `HTTP` client. 

I'd like to propose the idea of removing Guzzle entirely, and to provide a way for users to provide their own compatible `HTTP` client. For now I'm not able to add this `SDK` to project with e.g. `Guzzle 7`.

**Comment by Samik081** [comment]
Hey @kadryjanek, thank you for opening the issue and big sorry for the delay with the answer (we did not have notifications on the issues configured, and nobody was able to spot it 🙈).

I totally agree with you, and we'd love to remove that dependency. 
Unfortunately for now, this SDK is mostly auto-generated via the [**swagger-codegen**](https://github.com/swagger-api/swagger-codegen) based on our OpenAPI specification, with just few adjustments for authorization. Because of the fact, that the **codegen** generates the code already coupled with Guzzle, we are not able to that easily get rid of it.
This will probably change in the future, as we plan to give this SDK more love at some point (and maybe just rewrite it on our own), but until that time, Guzzle has to stay with us :(

Nevertheless, both `6` and `7` versions of `Guzzle` seem to be compatible with this lib, so I have also allowed `Guzzle 7` in the `composer.json`, so you should be able to require it in your project now (https://github.com/DocPlanner/integrations-api-sdk-php/releases/tag/v1.0.20.1).
